# Generated by Django 5.1.5 on 2025-01-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('user_role', models.CharField(choices=[('Organizer', 'Organizer'), ('Delegate', 'Delegate')], default='Delegate', max_length=10)),
            ],
        ),
    ]
