# Generated by Django 5.1.5 on 2025-01-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_alter_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
