# Generated by Django 5.1.5 on 2025-01-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concert_name', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('venue', models.TextField(max_length=500)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_tickets', models.PositiveIntegerField()),
            ],
        ),
    ]
