# Generated by Django 5.1.5 on 2025-01-24 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concert_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concert',
            options={'ordering': ['date_time']},
        ),
    ]
