# Generated by Django 5.1.5 on 2025-01-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert_booking', '0002_ticketbooking_delete_concertbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketbooking',
            name='tickets_booked',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
