# Generated by Django 5.1.5 on 2025-02-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert_booking', '0003_alter_ticketbooking_tickets_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbooking',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
