# Generated by Django 5.1.5 on 2025-02-03 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concert_booking', '0004_ticketbooking_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketbooking',
            name='qr_code',
        ),
    ]
